// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"AltTreasury/internal/biz"
	"AltTreasury/internal/conf"
	"AltTreasury/internal/data"
	"AltTreasury/internal/server"
	"AltTreasury/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	treasuryRepo := data.NewTreasuryRepo(dataData, logger)
	treasuryUsecase := biz.NewTreasuryUsecase(treasuryRepo, logger)
	treasuryService := service.NewTreasuryService(treasuryUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, treasuryService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, treasuryService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
